language: perl
perl:
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"
before_install:
  - sudo apt-get install libgd3 libgd-dev libgd-perl libgd-graph-perl libgd-text-perl
script: "perl Makefile.PL && make disttest"

